export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/'
export const BOOK_ROUTE = '/book'
export const USER_ROUTE = '/user'
export const READING_ROUTE = '/read'